### ISSUE TITLE
Threshold Pressure in a simple PMA model

### ISSUE THREAD

**Issue by JPL-BELG** [OpenWaterAnalytics/EPANET#621] opened 2021-01-01 20:34 UTC
Using the PMA model for the first time, I test it with a very simple model including only:
- a tank (R001) with constant section, emptying to a single node (N001) through a single pipe (E0001)
- a constant demand in N001 : 15 lps

In that model, the node demand and the pipe flow must be the same ones.

The data relative to the PMA are:
![image](https://user-images.githubusercontent.com/12865835/103445681-c8e1ea00-4c77-11eb-9849-4e0825e5f275.png)

The hydraulic time step is 15 minutes (00:15).
Due to the constant demand from the tank and no inflow, the water level should linearly decrease until the “Required Pressure” (2.0m) where the flow (equal to the node demand) must decrease according the PMA model.
![image](https://user-images.githubusercontent.com/12865835/103445686-d7300600-4c77-11eb-91fa-de71cbc0f792.png)
![image](https://user-images.githubusercontent.com/12865835/103445690-e616b880-4c77-11eb-90d8-4b2dddd4e852.png)
 
One can see that:
- the flow is 15 lps until around the “Minimum Pressure” (1.1m here at 05:00) and not the “Required Pressure” (2.0m): PROBLEM
- at the next time step (05:15), the pressure increases and is now interpolated between “Required Pressure” and “Minimum Pressure” as it has to be
- the final evolution of the curve looks fine : flow/water demand vanishes when the water at N001 decrease to the “Minimum Pressure”.

It seems to be an issue due to a confusion between the two Pressures when reaching the threshold where the demand depends on the pressure.

Thanks for your opinion.

**Comment by LRossman** [comment] 2021-02-04 20:41
@JPL-BELG  thanks for posting this issue.

Last month I made a small change to the PDA code that fixed a non-convergence problem in a particular network. The modified code is in the `dev_PDA_mod` branch. When I applied this code to a model ([PDA-fail.inp.txt](https://github.com/OpenWaterAnalytics/EPANET/files/5928307/PDA-fail.inp.txt) ) like the one described here the incorrect PDA behavior was fixed. Below are two charts with results for my model for the node whose demand is pressure dependent between the limits of 1 to 2 m. The first is from running the current EPANET v2.2.0 and the second from the modified engine DLL in the `dev_PDA_mod` branch. The v2.2.0 result is not honoring the pressure limits correctly while the modified code is.
![image](https://user-images.githubusercontent.com/12769926/106950587-9dca3a80-66fc-11eb-84d1-0517cc46132c.png)
![image](https://user-images.githubusercontent.com/12769926/106950600-a4f14880-66fc-11eb-82fb-0a76dac45e80.png)
I need to test the modified PDA code on some more networks to make sure it's robust and also resolve why it failed the PR regression test on one particular network (which appears to be due to a minor difference) before it can be merged into the `dev` branch.

**Closed** 2022-06-29 15:35 UTC
