### ISSUE TITLE
Refactor parallel link detection algorithm

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#351] opened 2018-11-29 12:55 UTC
Implemented and rolled back in PR #350. Let's implement it in a separate PR instead.

**Comment by LRossman** [comment] 2018-11-29 14:10
@michaeltryby I'm confused about this issue. PR #350, which has been merged into `dev`, already contains the equivalent of a rollback since the CI tests wouldn't pass without it. So I don't see what further action needs to be taken regarding parallel links.

**Comment by michaeltryby** [comment] 2018-11-29 15:34
@LRossman Sorry about the confusion. Please allow me to explain. 

Lumping together tens of thousands of changes covering declared and undeclared issues makes it difficult for the few of us that are interested to follow what you are doing. When you create an Issue and pair it with a PR you are creating a scope for the changes that makes it easier for other developers to understand what is going on. 

There was no declared Issue for refactoring the parallel link detection algorithm and it seemed out of scope for PR #350 titled "Code Cleanup". So the first point of confusion comes from a misunderstanding about what you consider code cleanup and what I consider code cleanup. I took code cleanup to mean cosmetic changes as you described in Issue #338. I created this new Issue to create a scope for the other refactoring changes you wish to make. I know it seems like a lot of bother, but this communicate with other developers and create a record for what is going on. 

Another potential point of confusion revolves around regression testing. When tests fail and everything checks out, I'm happy to work with you on updating the benchmark as we have already done several times already. Updating the benchmark is part of the workflow. We need it to help keep bad commits and bugs out of the repo. I get that reg testing severely cramps your style. Sorry about that, but it's here to stay.

**Comment by LRossman** [comment] 2018-11-29 16:18
@michaeltryby no need to explain as I can understand how things got confusing because of the CI failures - first due to the `test_setid` unit test and then due to the change in how parallel links were being processed. I suppose we have different definitions of code cleanup. Mine includes eliminating an unnecessary data structure (the node incidence lists used for WQ analysis) when an already existing data structure (the node adjacency lists used for hydraulics) could be used instead. 

And just for the record, I fully support the need for regression testing. My frustration is with the lack of information that the testing provides on where failures occur and for what reason.

**Closed** 2018-12-06 15:57 UTC
Labels: enhancement
