### ISSUE TITLE
New functions documentation

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#24] opened 2015-09-14 18:33 UTC
Apart from the [changes documentation](https://github.com/OpenWaterAnalytics/EPANET/issues/14) I think we should document the new files added to the DLL. There are about 10 of them and I think that we could start with Wiki pages right here on GitHub.

**Comment by samhatchett** [comment] 2015-09-15 13:36
i'm wondering about the most effective way to handle documentation. i've seen projects use doxygen for all the api docs, and this will integrate nicely with most IDEs' inline help features, and would automatically generate web-based searchable documentation. I haven't really used the GitHub Wiki feature, so i'm not as familiar with it, but it looks like there's limited capability for git-based branching and merging for wiki pages, and some control over push permissions. any thoughts?

**Comment by eladsal** [comment] 2015-09-15 17:39
Not sure that the GH wiki is the right place but it is just there. At the moment we don't have many new functions so it's not that hard. The main issue is writing the text.

Anyone knows if there is an editable version of the Toolkit's help file?

**Comment by michaeltryby** [comment] 2015-09-15 18:15
Lew developed the EPANET help files using "Help and Manual" available from EC software. I have the files but they are in a proprietary format. They can probably be wrangled into RTF or HTML. 

Here is a nice example of how GitHub can be used for developer documentation. 
https://atom.io/docs

**Comment by samhatchett** [comment] 2015-09-15 18:23
i don't think that the Atom docs were generated using publicly available GitHub documentation technologies. They are very nice though.

**Comment by michaeltryby** [comment] 2015-09-15 18:29
Yeah you're right. Might be overkill. https://atlas.oreilly.com/

**Comment by tudorbarascu** [comment] 2015-09-15 18:46
Hi guys, how does [sphinx-docs](http://sphinx-doc.org/index.html) look to you?
It can be used with transifex for translation, can output html, ePub, pdf's etc. and it's used by a lot of projects for documentation (python, mapserver etc.
See http://docs.pylonsproject.org/projects/pyramid/en/latest/index.html for an example.

**Comment by samhatchett** [comment] 2015-09-15 19:02
looks interesting - there are so many different options for documentation. most of all, we want whatever mechanism we use to be simple, easy to update, and low on dependencies. I can see a hardcore C programmer saying "wait, i have to install _what_ ?"

i've used doxygen for a long while, so that's my comfort zone and I appreciated how my IDE recognizes the markup... however i think flat text markdown files are really great too (as in github wiki or jekyll pages). I just want to make sure we impose the least amount of required education possible on other devs so that it's easy to contribute and not get frustrated.

**Comment by eladsal** [comment] 2015-09-15 19:35
In my view a solution that will produce a pdf\rtf\hlp (or something of that kind) is very important. We have user which use so many languages, not only C.

**Comment by eldemet** [comment] 2015-09-15 19:43
Yes. The file toolkit.chm is essentially a zip folder. By renaming it as
ZIP and extracting it, we get the HTML files for all the functions.

I think it would be easy to copy the help files in Github.

**Comment by eladsal** [comment] 2015-09-15 20:14
Just found out that the ["Github wiki of a GitHub repo is a git repo in itself"](http://stackoverflow.com/questions/18759738/effortless-export-from-github-wiki)

**Comment by michaeltryby** [comment] 2015-09-21 21:49
I decompiled the .chm using 7-Zip as per @eldemet suggestion. It generated a lot of .html files and some graphical assets. Hyperlinks throughout are broken.  

@samhatchett idea of maintaining API documentation inline with the source code is a good one. Problem is there is a lot of other useful documentation here that we need to find a place for like warnings and error codes, toolkit examples, input file format, and binary output file format. 

Suppose part could reside in a GitHub wiki and we could cross ref with auto generated API docs. Thoughts?

**Comment by samhatchett** [comment] 2015-09-21 23:02
Doxygen, which I'm familiar with, has good capability to add and link among standalone pages, as for tutorials and design documents, in addition to the inline api docs. I still feel that this could be a good route.

**Comment by eladsal** [comment] 2015-09-22 06:14
@michaeltryby:  it's not only warnings and error codes, toolkit examples and so on. I think when people read documentation they like to have things in one place. Take a look at the documentation for some functions like `ENsetcontrol` or `ENgetnodevalue`, do you think we could\should add all the information in the inline api docs?

**Comment by eladsal** [comment] 2015-09-22 06:20
One more thing, in the long run I think that we need a documentation solution that is separated from the main repository's permissions scheme.

**Comment by eldemet** [comment] 2015-09-22 06:26
I would also argee with @elad. I have started porting the htmls into the
wiki and we can distribute the work to reduce the load. We can then add
hyperlinks for cross reference.

Perhaps In the code we can add a hyperlink to the relevant documentation in
the github wiki

**Comment by eladsal** [comment] 2015-09-22 06:31
We can explore other documentation options but for version 2.1 the only **must** is the documentation for the new functions which are just a few.

**Comment by jamesuber** [comment] 2015-09-22 12:08
I don’t see the problem with having more than one documentation “solution”. Insisting on one seems to me like the wrong approach.

First, concise basic documentation that describes the API in a single sorted list of functions, linked to one page complete descriptions of each, seems to me a must for programmers. And that’s likely the only thing they will ever need. Having that documentation be automatically formatted from some sort of tagged in-line documentation system also seems to me of obvious benefit, cause it comes at a low cost and is accurate and uniform.

Then there is the documentation for people who are saying “Does Epanet have an API?” or even “What is an API”? These people are going to want tutorial explanations, examples, overviews, machine and language dependent usage tips (e.g. the pointers issues). Probably they’ll want to be pointed to a FAQ for a shortcut to answers. As far as I am concerned, such documentation could exist anywhere, and be constructed by any process, so long as it is trivially available and easy to maintain. I assume that a wiki fits that bill. 

And I’d assume the wiki docs would simply include as one section the concise basic documentation, for reference, updated automatically from the inline documentation. 

So, I agree with everyone ;-)


 <http://www.citilogics.com/> JIM UBER <mailto:jim@citilogics.com> • 513.368.6303 <tel:513-368-6303> • CITILOGICS.COM <http://www.citilogics.com/>

**Comment by eladsal** [comment] 2015-09-22 12:48
@jamesuber I would estimate that 99% of the Toolkit users are not programmers. Most of them might be engineers who write code :)

I can't find the source rtf file of this [pdf](http://iridia.ulb.ac.be/~manuel/doc/toolkit_help.pdf) - anyone?

**Comment by jamesuber** [comment] 2015-09-22 13:45
I think you are just saying that 99% of toolkit users will preferentially want to access something like a wiki for docs. We could debate that but ok. 

Does that mean we should not use an inline doc system for the other 1%? Especially since the output of that process is what I'd consider to be critical and crucial basic reference documentation for the non-programmers too. 

Are you suggesting that the non-programmers don't want or need reference docs? If not that, then how should such ref info be generated and maintained? By looking at the code with my eyes and typing into the wiki with my fingers? 😉

I'm just trying to shortcut to a hybrid solution that just seems obvious to me.

**Comment by samhatchett** [comment] 2015-09-22 14:59
Inline documentation for the API just makes too much sense. It's already there in Lew's code, just not to the javadoc/doxygen standard that would allow you to generate more user-friendly pages from it. Inline dox means that it is trivially easy to ensure that the intention of the programmers regarding usage of the functions is communicated, and that those messages are updated as the code is updated.

OTOH, there is certainly a load of people who will just want to know how to download this thing and run it command-line style, or plug it into MatLab to run a prepackaged visualization script. For those uninterested in the API, a wiki makes perfect sense. An instructional tone for particular walk-throughs and demonstrations fits well into a wiki, as does documenting the underlying hydraulic methodologies and citing research - think all the appendices in `en2manual.pdf`. 

But when we talk about demonstrations of the API usage, my sense is that this belongs back in the auto-generated documents, or as separate "demo" compilable code within the repo since that is so intimately tied in to the "programmer" perspective.

Inline documentation has the added benefit of working over the exact same channels as regular code commits -- through issues and pull requests.

Finally, an example of what I consider a truly imitable approach: "Core Plot" is an open-source framework that I've used to enable scientific graphing in some Mac- and IOS-based applications. This is a team of seasoned professionals, and they've settled on a hybrid approach. Their [GitHub Project page](https://github.com/core-plot/core-plot) will link you to both the Wiki, and the API docs. The Wiki uses GitHub's native wiki platform to  orient users with a design overview, a list of companies using the software, examples of what the tool can produce, special notes for linking and compilation, and notes about unit testing and contributions. Then they use the [API docs](http://core-plot.github.io/MacOS/index.html) for establishing the expected behavior of all the framework classes and functions, and link you to example applications within the code repository. All this inline documentation is used to generate static html files once per release version (and those files are hosted on GH Pages), and the markup within the header files is helpfully parsed by my IDE so I can see quick hints on usage as I'm generating my own code. This last piece is *truly* invaluable to me as a developer and makes using this framework so very easy and fun.

I hope all this makes sense and is not overwhelming. In the end, I agree with @eladsal when he says that the only "must" is documenting and demonstrating the new API functions. For that - as in, for the 2.1 release, we need only set our sights high enough to accomplish this. While it's important to have the discussion and lay out a plan going forward, the bare minimum will be to document the new API functions within the code (as per existing convention, or as javadoc-style markup), refer to their existence, and provide sample code similar to the snippets contained in the `toolkit_help.pdf` file that @eladsal linked to which outlines usage of the toolkit.

**Comment by eladsal** [comment] 2015-09-22 15:31
@jamesuber: no, I'm not saying we should not use an inline doc system, we can have that. I think that most users will benefit more with something that hold more information like for example the info in the Toolkit help file (see for example the help for `ENgetnodevale`). If something like this could be generated from an inline doc system then why not use it.

@sam I don't think that the average Toolkit user will find a page like [this](http://core-plot.github.io/iOS/interface_c_p_t_plot_space.html#aec95993371f85fbd12c7327722181226) very easy to work with.

**Comment by eladsal** [comment] 2015-09-22 15:36
BTW, I have added basic documenation to all the functions in `epanet.c` which were missing it and to all the new function I added. At the end of the day the main task is writing the documentation ...

**Comment by samhatchett** [comment] 2015-09-22 15:57
Inline documentation is often wisely accompanied by expanded user-manual style material.
I have another prime example: http://doc.cgal.org/4.2/CGAL.CGAL.2D-Arrangements/html/index.html#Arrangement_on_surface_2ASimpleProgram

... this just shows what is possible with inline documentation. real code snippets, equations, images, graphs...

**Comment by eladsal** [comment] 2015-09-22 16:18
@sam nice, this is a very impressive example.

I think that what we need from the documentation solution(s) is:
1. easy to write - wysiwug editor. I wouldn't like someone who wants to contribute to the documentation having  to learn Git.
2. easy to maintain
3. have an option to export to a stand alone doc (pdf)

I'm not sure that currently I can really understand the needs of an engineering masters student who took one course in programming and now want to write code with EPANET. I have a feeling that we have many users like that.

Maybe we should keep this issue open for now and not make a decision yet. We can just put basic info for the new functions in the wiki for 2.1.

**Comment by sam** [comment] 2015-09-22 16:37
@eladsal: Wrong @sam. You want @samhatchett.

Just FYI. I get automatically subscribed to threads that at-mention me. Github's fault. Not yours. :-/

**Comment by eladsal** [comment] 2015-09-22 16:41
@sam sorry about that. I'm sure all the Sams on Git envy you for being the first Sam :)

**Comment by samhatchett** [comment] 2015-09-22 16:47
for a minute i thought @jamesuber was being rude

**Comment by michaeltryby** [comment] 2015-09-22 17:17
Are we in agreement on Doxygen for the inline source docs? I suggest we give GitHub Wiki a trial run and see how the Toolkit documentation works out. Markdown is popular, easy to learn, and a portable format. We have little to lose.

**Comment by michaeltryby** [comment] 2015-09-23 20:22
Looks like one issue with GitHub Wiki's is that it's not straightforward to fork them. Like if we want to share work between repos.

**Comment by eladsal** [comment] 2015-09-23 20:24
I also could not clone it on my desktop (Windows). Keep getting an error.

**Comment by samhatchett** [comment] 2015-09-28 13:52
so, as for the doxygen route: i've implemented a few doxy-compatible comment blocks in the `doxy-trial` branch. [Look in epanet2.h](https://github.com/OpenWaterAnalytics/EPANET/blob/doxy-trial/include/epanet2.h) -- The output that all this generates can be seen [here](http://samhatchett.github.io/epanet-dox/modules.html) - this will take you to the "modules" listing, which paginates groups of API functions to manage the complexity of the whole collection of functions.

this approach tends to expand the length of the header file, but in my view makes the whole project more usable when taken in context of having access to an IDE and a web browser. What do you think - is this a good route for auto documentation?

**Comment by eladsal** [comment] 2015-09-28 16:47
I'm not sure yet. I perfectly understand the need for IDE documentation and guess that is why it's in the header file. However, that is mostly for C users, right? .NET, VBA and other platforms don't use the epanet2.h header file.

Marios added a few functions pages in the Wiki ([ENopen](https://github.com/OpenWaterAnalytics/EPANET/wiki/ENopen)) and I tried one too ([ENepanet](https://github.com/OpenWaterAnalytics/EPANET/wiki/ENepanet)). I think these pages would be static without many edits to them so need for a lot of maintenance. The links to these functions from the general Wiki documentation is a plus.

How about a combination of the Wiki and thin inline documentation in the header file with links to the Wiki version of each function?

**Comment by eldemet** [comment] 2015-09-28 18:04
I would also agree at a combination if possible with a link in doxygen
syntax pointing to the relevant wiki page.

**Comment by samhatchett** [comment] 2015-09-28 18:28
I'm at a bit of a loss here - trying to figure out a compelling reason to repeat information (breaking the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle). Surely there's a way to keep relevant API tech specs near the code, and still make use of the wiki without creating this fragile situation of duplicate entries for function docs. Is it the appearance of the Doxygen pages? I'll admit they are ugly, but there are many custom CSS files available to ease that. Is it the organization? Doxygen allows for custom pages, internal links, arbitrary mainpage, really any sort of document organization you like.

@eladsal I mostly agree with your list of three goals (to quote):

>1. easy to write - wysiwug editor. I wouldn't like someone who wants to contribute to the documentation having to learn Git.
>2. easy to maintain
>3. have an option to export to a stand alone doc (pdf)

... except perhaps the first point. there are certain documentation (like API docs and demo code snippets) that should probably only be handled by people familiar with contributing software. Considering that, all of these issues are met well by doxygen. I'm just not seeing the advantage to repeating any of this material in the wiki.

on the other hand, i don't see a real disadvantage to just linking from the wiki to the API docs for people interested in that side of the project. I think the wiki is fantastic for documenting the input/output formats, standalone command-line arguments, hydraulic theory, etc., but as the number of wiki pages and their doppelgänger doxy pages increases, this will become a major headache fast.

**Comment by eladsal** [comment] 2015-09-28 18:58
@samhatchett I agree that repeating information should be avoided unless there is a good reason for it.

Take a look at `[EMepanet](https://github.com/OpenWaterAnalytics/EPANET/wiki/ENepanet)` for example. We can have a Wiki page with just a link to the doxygen docs or a thin inline doc with a link to Wiki. I think that currently it's easier to maintain the Wiki, have other people contribute and easier to write there. Also when 2.1 is out and you can't really change anything in the documentation since `epanet.h` is tagged.

If the case was that most of the code and APIs are not static (and they will be since we would like to have backward compatibility) then I would certainly go with automatic doc generation.

**Comment by jamesuber** [comment] 2015-09-28 20:33
I think we are developing a documentation approach that will serve us long term. So, not 2.1, but 3.0+. I also believe that we are all thinking about some significant code re-write  in the future. Some are even advocating for an OO architecture. We will absolutely need code level documentation that tells programmers how to use the methods. Most of those methods will be new. There’s no way that such documentation can be done as a separate task — it just won’t happen, or it will happen too late. Do I have that about right?

It seems that everybody who is developing the code base will have to, eventually, get used to the idea of using Doxygen (or something like it). I just don’t see a way out of that, since we’re talking about collaborative code development and the documentation must adapt.

Can I ask for clarification, beyond 2.1, about what standard the devcom is going to adopt for these code level docs. In my mind that decision is separate from any other discussion related to 2.1 documentation.
 
For 2.1 only, it would be great for the devcom to exercise those same code level documentation methods in order to get used to them. It sounds like Elad is fine with that (i.e. that the wiki can “link to the Doxygen docs”). So the only issue seems to be whether we also type in the same function descriptions into the wiki. I agree with Sam that the wiki is most effective for user documentation outside of the function descriptions, and I also don’t really understand why we’d want to spend time repeating the function descriptions, when the same time could be spent documenting other things. But, the most important thing is that we have a long term vision of using code-level documentation as the code base moves forward and changes.

-Jim


JIM UBER <mailto:jim@citilogics.com>  •  513.368.6303 <tel:513-368-6303>  •  CITILOGICS.COM <http://www.citilogics.com/>

**Comment by michaeltryby** [comment] 2015-09-28 20:38
@jamesuber I'll second that. Maintaining documentation inline with the source code is of primary importance. If Lew hadn't done it, we probably wouldn't be having this conversation cause no one would be using his code.

**Comment by eladsal** [comment] 2015-09-28 21:14
@jamesuber:
> It sounds like Elad is fine with that (i.e. that the wiki can “link to the Doxygen docs”).

I actually think the opposite. Sorry it wasn't clear.

>So the only issue seems to be whether we also type in the same function descriptions into the wiki.

We aren't typing anything (almost). We are copy-pasting the help file into the Wiki and doing a bit of formatting. I still don't think we have to decide now (2.1). This can easily wait for the next version. We have the current documentation and other tasks are more important.

@michaeltryby:
>  Maintaining documentation inline with the source code is of primary importance. If Lew hadn't done it, we probably wouldn't be having this conversation cause no one would be using his code.

I think that the help file was the most important documentation since it hold much more information about the functions.

**Comment by jamesuber** [comment] 2015-09-28 21:54
I don't want to wait to decide the issue of code level docs cause we're on it right now and nothing is going to change. 

Elad, you are being very persistent about this issue. You are entitled to your opinion as anyone else, but you need to state why you are so against doing code docs in doxygen as a project standard. The wiki can stand, and evolve, and nobody is going to get everything they want here. So why exactly won't you jump on board the idea of doxygen docs, as several have already described in detail why their efforts would be helped by doing so?

Let's move past this.

**Comment by eladsal** [comment] 2015-09-28 22:19
@jamesuber it's not personal.

I'm not against doxygen I'm for the wiki at this stage. I have already written why I think the Wiki is better but here again are a few points:
* easy to write - wysiwyg editor
* easy to collaborate for non GitHub users
* have everything in one place (which is better but not a must)
* ability to change the documentation without having to change the source code (if the docs are in the header file).

Let's have a short inline version and the help file in the wiki. I'll do the wiki part, it's almost done.

> I don't want to wait to decide the issue of code level docs cause we're on it right now and nothing is going to change.

According to you the code is going to undergo significant re-write so that would be a big change and a good point to decide on inline documentation. Currently we have almost all the documentation in the wiki and I see no good reason to make a change at this point.

I agree, let's move past this, it's not urgent.

**Comment by samhatchett** [comment] 2015-09-28 23:29
I think the "easy to write" isn't really a strong reason - do we expect that the API reference is going to be generated or edited by people who can't look at code or markup? When the code changes, the API reference needs to change too - this is why inline dox is just such an awesome idea. The point is that these different API references will diverge, and quickly. Maintaining the redundancy takes talented people away from more important work. The fact that it's almost complete in the wiki isn't a great reason to finish it, if it's the wrong decision. And I get the impression from the amount of dialog here that we're not agreeing about what the right decision is.

i would argue that this is urgent. A 2.1 release is an opportunity to strike the right tone and set up the processes that we will use going forward to version 3+ and beyond. Of course, this dialog is part of that process - I would encourage us to  come into agreement before building too far in one direction.

There are 15 people "watching" this repository, which means that they are getting these notifications. Do any of you have opinions or experience to share?

Failing consensus, more input, or a vote, it seems that the next-best approach is to let 1,000 flowers bloom. We expend more effort in the beginning to have 2 different parallel API references and deal with the divergence issues when they arise.

**Comment by eladsal** [comment] 2015-09-29 06:39
@samhatchett 
> When the code changes, the API reference needs to change too

It's not only API reference. We all know that the code is not going to change unless it undergoes a major rewrite as @jamesuber said (BTW, it might not be even in C). We are not breaking backward compatibility so the reference is going to be very static. However, let's say 2.1 is out with inline documentation and now a vb.net user wants to add a vb.net code snippet to one of the function's docs. First of all he can't since there is no editing of tagged files. Second, he will need to add his vb.net snippet in the `epanet2.h` header file (the file for C programmers) and in doxygen format (unless you suggest he adds it in a different place which doesn't make sense). Sorry, I don't see this happening. I guess you do not plan to add the docs to other header files too.

All, no need to wait. The votes are clear on this and we can close the issue. Go ahead with doxygen.

**Comment by samhatchett** [comment] 2015-09-29 12:41
Thanks all for being engaged and respectful. This thread is a bit long, so I'd like to close this issue and break it out into some other items that have come from this discussion - namely the doxy markup enhancements, and vb.net documentation.

The only other thing I might reiterate for this discussion is that doxygen is extremely flexible. Function documentation doesn't need to exist all in the header files, or even in the same file; a single function can be documented in whole across several different files, including markdown files, even markdown files in special directories - which are accessible through GH's pseudo-wysiwyg markdown editor. It's plenty of rope to hang oneself, and the trick is just to get it all set up in a way that meets our needs.

**Closed by samhatchett** 2015-09-29 12:41 UTC
Labels: documentation
