### ISSUE TITLE
Setup automated testing using Appveyor and Travis CI

### ISSUE THREAD

**Issue by AbelHeinsbroek** [OpenWaterAnalytics/EPANET#97] opened 2016-11-23 10:19 UTC

**Comment by samhatchett** [comment] 2016-11-23 14:27
we do have a travis script set up for rudimentary testing - which is unfortunately broken at the moment. @michaeltryby has a better testing framework that he's said he would like to contribute, so i suggest waiting to hear from him on that issue.

**Comment by michaeltryby** [comment] 2017-06-16 18:02
@AbelHeinsbroek @samhatchett I have some work on numerical regression testing that I could share. It's based on python `nrtest`. It's pretty much the same thing I just checked in for [SWMM](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/tree/dev) except for EPANET. It works great for benchmarking engine work locally. We will have to adapt it to the CI workflow but I think its a solid foundation for doing that. 

Sorry for the delay. I am officially working on EPANET now.

**Comment by michaeltryby** [comment] 2017-06-16 18:13
The tools needed to run nrtest are staged [here](https://github.com/USEPA/Water-Distribution-Network-Model/tree/dev/tools). I can checkin a stub for epanet-nrtestsuite as well. 

I've done a little refactoring on the [outputapi](https://github.com/USEPA/Water-Distribution-Network-Model/tree/dev/tools/epanet-output/src) cause I wasn't doing the opaque pointer the right way. I can also switch the [python wrapper](https://github.com/USEPA/Water-Distribution-Network-Model/blob/dev/tools/epanet-reader/epanet_reader/outputapi.py) from ctypesgen to SWIG. What do you think?

**Comment by michaeltryby** [comment] 2017-06-17 16:38
Turns out handling opaque pointers in SWIG is a bit tricky: [SWIG Opaque Pointer](https://github.com/swig/swig/wiki/FAQ#q-how-do-i-interact-with-functions-that-require-double-void-pointers---void-)

**Comment by samhatchett** [comment] 2017-06-19 14:49
thinks for digging into this @michaeltryby ! while not trivial, at least it's possible with swig. I say we go ahead with it. based on some of the [discussions here](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/44), it sounds like using swig as the generic wrapper interface is a good move. Since that is perhaps a separate issue from just doing automated tests, I will create a new issue for that and tag it on the roadmap. Still open to discussion of course, if anyone has feedback!

**Comment by michaeltryby** [comment] 2017-06-26 19:29
@samhatchett I would like to check in my current `nrtest` tooling. Do you have a preference what branch I pull against?

**Comment by samhatchett** [comment] 2017-06-26 19:51
@michaeltryby please update from `feature-nrtest` and PR to that branch. thx 😉

**Comment by michaeltryby** [comment] 2017-07-02 19:20
`nrtest` works great for bench marking EPANET locally. I believe we will have to resolve the following issues in order to get `nrtest` running under CI: 

- Comparison tolerance rtol and atol for `nrtest` are specified from the command prompt. It would be better if comparison tolerances were persisted with the test descriptions. Values passed from the command prompt should override those defined with the test description. So either `nrtest` needs to be forked and modified or the run script called from CI can call each test individually with tolerances. 

- To run an executable `nrtest` requires the absolute path to be defined in the app description or it must be on the system path. `nrtest` is designed to run a setup script prior to calling the executable. To run under CI the setup script would need to add the executable to the system path. 

- Python based EPANET test tools need to be built, packaged, and installed prior to running `nrtest`.  The Python environment on the CI server has to be configured to satisfy test tool dependencies.   

- Write a run script for the CI server to execute (see above).

- I'm sure there are others I can't think of ...

Thoughts?

**Comment by samhatchett** [comment] 2017-10-27 14:53
looks like this issue is basically resolved. further enhancements to testing can be fielded in other issues. thanks all!

**Closed by samhatchett** 2017-10-27 14:53 UTC
