### ISSUE TITLE
ENsetnodevalue for Tank using EN_MINLEVEL/MAXLEVEL returns error if Tank has a curve

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#29] opened 2015-09-22 20:22 UTC
expected behavior is to be able to set the min/max level for a tank, even if it has a volume curve

**Comment by eladsal** [comment] 2015-09-26 18:01
I think this is not a bug but a feature. The error returned is specific for this case. See [here](https://github.com/OpenWaterAnalytics/EPANET/blob/dev-2.1/src/epanet.c#L2122). I agree this should be changed to allow updating min\mac levels if a tank has a curve.

**Comment by samhatchett** [comment] 2015-12-04 03:52
This would be an easy tweak for 2.1 -- would anyone rather kick it down the road?

**Comment by eladsal** [comment] 2015-12-04 09:11
I have looked again on the code and there are some issues with it even before we deal with the curves (should be for 2.1):
*  no error is returned when node is not a tank 
*  no check that Hmin<HMax 
*  no check that H0<HMax 
*  no check that H0>Hmin 

and then we need to add: 
*  Hmin and Hmax are within the curve
*  calculate Vmin
*  calculate vmax

Anyone see something missing?

**Comment by michaeltryby** [comment] 2018-09-12 17:38
@eladsal and @samhatchett What needs to be done to close this Issue?

**Closed** 2019-05-11 12:53 UTC
Labels: bug, enhancement
