### ISSUE TITLE
EPANET Version 2.2 Release: Establish new feature deadline 

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#245] opened 2018-08-29 13:01 UTC
Many contributors have checked in great work and together we have accomplished a lot. It is time to think about finalizing version 2.2 and making a release. 

My inclination is to set a reasonable deadline for the inclusion of new features, and then focus our efforts on testing, documentation, and packaging. I am throwing out a straw man deadline of September 30th, 2018 to get people thinking and discussing.  

Opening the door for v2.3 goes hand in hand with closing the door on v2.2. Therefore, I don't think there is a need for an "epic" development drive to get your stuff in (although a moderate drive would be nice 😆). If you feel like you can't make this new feature deadline no worries; we will include it in v2.3dev. 

How do you feel about this proposal? Please feel free to share your thoughts. Thanks!

**Comment by samhatchett** [comment] 2018-08-29 14:15
how do you think the time-based deadline relates to the [Milestone v2.2](https://github.com/OpenWaterAnalytics/EPANET/milestone/4)? Do you see adding/removing issues, or just bumping issues that don't make the date cutoff?

While it would be great to feel some progress on the project, there doesn't seem to be anyone "clamoring" for getting v2.2 by a certain date. Unless I'm unaware of downstream needs? I think it makes more sense to set reasonable feature and testing goals, and then move toward that, holding the release date loosely. 

Perhaps the more important conversation is along the lines of determining which issues on the 2.2 milestone are really essential for the next release. There are broken/incomplete features, along with untested additions, among those issues that really do need to be addressed, regardless of deadlines.

To be clear, I am totally fine with setting date expectations. But let's just notice that most everything on milestone 2.2 is fix or cleanup-related (aside from the mass-balance problems and Lew's feature additions like #165). So deadline or not, the release won't make sense without closing those issues first. So in my thinking, we need to first agree on the set of milestones, assign any issues that are unassigned, and then poll the active contributors for when we can all agree to have things done and merged. That's where the deadline comes from.

**Comment by michaeltryby** [comment] 2018-08-29 15:12
Internally here at US EPA, we are planning the next release. I guess this Issue is an announcement of our intentions. Just to be clear, what I'm proposing is a "new feature deadline." Not complete the entire thing deadline. Fixes and cleanup can still occur as part of the release process after the door has been closed to new features. Make sense?  

There are two schools of thought. One, the features dictate the deadline. Or two, the deadline dictates the features. I lean towards the latter. I dislike deadlines, but I have to grudgingly admit that they do help me get things done. The idea is to set a deadline to gently organize the community. Just like deadlines we are all used to, like submitting conference abstracts. 

Looking over the list of Issues tagged v2.2 Milestone is one way to judge this milestone. The other way is to look at the 200 commits that have already been merged. We have done more than enough to declare a release. I agree we should prioritize the remaining v2.2 Milestone Issues and complete as many of the important ones as possible. If some role over, so be it. 

I actually, think we are mostly in agreement on this.

**Comment by LRossman** [comment] 2018-08-31 15:54
I would vote to postpone a new release until we can finish up the work on issues #160 - #165, four of which have already been completed leaving just #160 and #164. Granted there has been a great deal of work on wonderful new API features, such as concurrency and network building. But these have a limited audience of custom model developers. The six new computational features in #160 - #164 can be easily incorporated into EPA's UI (either new or legacy version) thus making them available to a much wider spectrum of users. (Actually only #161 and #163 require UI updates). So can we wait a month or so until we can complete tackling the low flow and quality mass balance issues to produce an updated engine that addesses all of the most significant computational shortcomings of the current one.

**Comment by michaeltryby** [comment] 2018-08-31 17:34
It's the "or so" that has me concerned! 😉

**Comment by michaeltryby** [comment] 2018-10-12 13:51
@LRossman has completed his work on Issue 160-164. Issue #165 remains open, since he felt his solution needed more work. My proposal to call a new feature deadline at this point went over like a lead weight. :wink: 

Can we discuss and build some consensus on a path to get us to v2.2.0 release?

**Comment by LRossman** [comment] 2018-10-12 14:37
Speaking for myself, I have completed work on all of the new features/upgrades that I committed to at the April ASCE/EWRI Modeling Summit. However there still seem to be a few loose ends that need to be addressed:
- the `writecon` issue #300 (working on it today)
- a possible issue with detecting warnings v. errors (still needs to be tested)
- completing the 2.2 Release Notes (I hope @eladsal can help with this)
- any of the other 81 open issues that might seriously affect the program's behavior.

I propose 11/1 as a hard date for a v2.2.0 release.

**Comment by michaeltryby** [comment] 2018-11-05 17:35
I propose we create a release branch with a focus on testing and bug fixes. Feature development can continue uninterrupted in the develop branch. Any changes occurring in the release branch can be merged back into develop once the release has been finalized.

**Comment by eladsal** [comment] 2018-11-05 17:47
We can go over the issues tagged for v2.2 and decide if we move them to 2.3
https://github.com/OpenWaterAnalytics/EPANET/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.2

**Comment by michaeltryby** [comment] 2018-11-05 17:49
@eladsal sure sounds good!

**Comment by michaeltryby** [comment] 2019-02-27 13:07
More water has passed under the bridge. Are we feature complete for version 2.2 now?

**Comment by LRossman** [comment] 2019-02-27 14:08
I would still like to devote some more time to discovering if there is anything askew from using the 2.2 API to directly manage a network data base under an interactive User Interface (like the legacy 2.0.012 Delphi UI or the new PyQt one being developed) , where users switch between editing network data, running a network analysis and viewing analysis results. This type of use case was one of the rationales for developing such an extensive API. I've already posted a few issues and made some fixes with regard to this. I'd like a little more time (no more than two weeks) to complete my analysis.

**Comment by michaeltryby** [comment] 2019-02-27 14:35
@LRossman I interpret that as, “yes we are feature complete.” Your analysis qualifies as QA/QC on the model building API.

**Comment by jamesuber** [comment] 2019-02-27 14:52
I just wanted to add - somewhat trivially I know - I think the API extensions are a great effort. This “feels” like something significant that will add a lot of weight to your 2.2 efforts. Congrats to all contributors!

**Comment by michaeltryby** [comment] 2019-02-27 15:06
@jamesuber I totally agree. Great effort!

**Comment by eladsal** [comment] 2019-04-14 19:13
All, can 2.2 be finalized? what are the must haves that we still need?

**Comment by LRossman** [comment] 2019-04-14 20:40
Of the open issues I can only identify three that people are working on:

1. #432 (have `EN_addnode` and `EN_addlink` return the index of the new object - @Mariosmsk and @LRossman  )
2. #452 (incorporate a generic linked list library into the code - @michaeltryby )
3. #458 (check for valid ID names in the `EN_addxxx` functions - @LRossman )

Of these I would say that only #458 is a must have (since it can be called a bug fix).

There is one more must have that is needed for the API to be complete. That is the ability to add and delete demand categories. Otherwise any network created by API function calls would be limited to using just a single demand category at each node.

I have already completed coding items 1 and 3 plus adding `EN_adddemand` and `EN_deletedemand` functions to my local version of `dev`. They just need some more testing before I can commit them which I hope to do this week.

**Comment by michaeltryby** [comment] 2019-04-14 23:28
We should clear any issues classified as bugs. There are 3 or 4 open issues classified as such mostly describing problems with tank levels. They may already be fixed.

**Comment by LRossman** [comment] 2019-04-15 01:54
I checked the 5 open issues that were marked as bugs and can summarize their status as follows:

1. #29 -Setting the min/max levels for tank nodes returns an error if the tank uses a volume curve. Actually the code now does nothing in this case. It should be fixed to re-calculate the min/max volumes from the curve.
2. #78 - There are cases where there is flow out of an empty tank or into a full tank. The 2.2 code is the same as the 2.1.012 code for this and only closes the connecting link if the head difference is > 0.0005 ft. I suppose that in some (rare) cases this tolerance is too lenient. (FWIW epanet-dev uses a direct test of positive flow out (or in) to close off the empty (or full) tank.)
3. #77 - Incorrect water age is computed for zero-demand nodes attached to closed valves. The revised quality algorithm may have corrected this. A test example should be run.
4. #124 - Fixed.
5. #150 - Fixed.

**Comment by LRossman** [comment] 2019-04-16 02:40
Regarding issue #77, I ran a test on a modified _example1.inp_ and could not observe anything wrong. See the attached image where the age of the closed valve's end nodes increases as time increases. In the absence of a more specific example I think we can say that issue #77 can't be reproduced.

![Issue77](https://user-images.githubusercontent.com/12769926/56178079-ddc3a900-5fce-11e9-9494-e13f83e6147c.png)

**Comment by michaeltryby** [comment] 2019-04-16 11:49
Please attach the inp file. I will add it as a reg testing case.

**Comment by LRossman** [comment] 2019-04-16 16:27
Re: my previous comment concerning the modified example1.inp: Here's what the age at the closed valve looks like using v.2.0.012 which is clearly incorrect since the pipes connected to the closed valve never see any flow:

![Issue77_2_0](https://user-images.githubusercontent.com/12769926/56226793-089b1500-6042-11e9-9aad-3109563d7afe.png)

I've attached the modified file with the duration reduced to 42 hours since that's enough to see the effect of the improved quality algorithm.
[example1_mod_age.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3085895/example1_mod_age.zip)

**Comment by michaeltryby** [comment] 2019-04-25 14:26
Lew has recommended leaving #29 and #35 open for the time being. That means that we have a potential release candidate here. 

Any thoughts or objections on declaring this the release candidate? Please feel free to share them.

**Comment by LRossman** [comment] 2019-04-25 14:34
Actually #29 has been resolved. I just left a comment in #466 asking for some more time to improve the way `demand.c` is used to manage demand categories.

**Comment by eladsal** [comment] 2019-04-25 14:35
> Any thoughts or objections on declaring this the release candidate?

@michaeltryby, by "this" you mean the current `dev` branch? running the `win_build` script I'm getting an error:
src\util/list.h(20) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory

**Comment by michaeltryby** [comment] 2019-04-25 15:03
Hey @eladsal, Yes that is correct. By "this" I mean the current state of the code in the `dev` branch would get promoted to release candidate. 

As for the `win_build` script, are you still compiling using Visual Studio 2010? There have been a lot of improvements in the code standards and compilers since then, including `stdbool.h`. We have been using Visual Studio 2017 on the `cmake` side for some time now. 

As far as I am aware, the `cmake` build is now capable of creating a dll usable by `VBA`. Correct? So I guess you can upgrade the compiler you use in your `win_build` setup or use `cmake`. You are welcome do whatever works best for your needs.

**Comment by eladsal** [comment] 2019-04-25 17:35
@michaeltryby maybe something is wrong with my setup, I will check.

However, what you are saying is that in almost your last commit you introduced something that breaks the build me and some others use and you want this to be the release candidate for 2.2? Maybe a workaround could be found to have 2.2 compatible with the old build.

**Comment by LRossman** [comment] 2019-04-25 18:00
There's an easy fix for this. Instead of declaring the `listIterator` callback function as `bool `in _list.h_ (hence requiring _stdbool.h_) it can be declared as `int `and replace the `true` value used in _list.c_ with `1`.

**Comment by michaeltryby** [comment] 2019-04-25 19:26
@eladsal Thanks for sharing your perspective. Based on comments you have made many times in our discussions here, it is clear that you consider backward compatibility an important objective. Is that a fair statement? I agree with you that backward compatibility is an important objective, however, what we must also consider is what we are giving up in order to maintain it. And we must make evaluations between what is gained and what is lost in order to maintain it. 

Because we can produce a 32 bit dll exporting std call using a .def file using cmake there is no reason that I am aware of not to use it. Other than, your preference for using the `win_build` script. I too have preferences. I have a preference for trying new things. So I tried using `stdbool.h`. How is your preference any different than mine? At a superficial level, there is no difference in our preferences. We each have a natural preference for doing things the way we like doing things. Pretty common stuff.  

The thing is, I want to modernize the project so I am interested in accessing all the great compiler technologies, and all the great language features that have come in since 2011. I would also like to standardize the build system. I want to close Issue #38. An issue that has been open since November, 2015. Lastly, I think standardizing on cmake will make the project cleaner and simplify maintenance for all of us. That is reasoning behind my preference. 

What is your reasoning for maintaining build backward compatibility and how does it compare to what the project is giving up for it?

**Comment by eladsal** [comment] 2019-04-28 15:49
Thanks @michaeltryby , I think working around stdbool.h as Lew suggested, will not really result in the "project is giving up" anything important.

**Comment by michaeltryby** [comment] 2019-04-28 21:22
@eladsal that doesn’t answer the question I asked you.

**Comment by eladsal** [comment] 2019-05-09 16:57
I'm reopening this issue since there are reference for issues which need to be resolved for 2.2

**Comment by samhatchett** [comment] 2019-05-09 17:33
can we put all 2.2 issues into the milestone, so it all gets linked together?

**Comment by eladsal** [comment] 2019-05-09 17:34
This:
https://github.com/OpenWaterAnalytics/EPANET/milestone/4

**Comment by samhatchett** [comment] 2019-05-09 17:36
right - I guess any discussion around particular issues should go into their respective threads. Otherwise I think that milestones are supposed to collect issues and track releases and things like that.

**Comment by eladsal** [comment] 2019-05-11 07:21
@LRossman you listed above #29 and #35, are those on the v2.2 list?

**Comment by LRossman** [comment] 2019-05-11 12:15
#29 has been resolved satisfactorily so it can be closed. #35 falls sort of in the same category as #165 (which is on the list), as both involve problematic dynamic tank behavior that appears rather infrequently and neither has been resolved in v2.2. So I suppose #35 should be added to the list. Also, #104 should be closed and removed from the list since it's been addressed.

**Comment by eladsal** [comment] 2019-05-11 13:21
Thanks @LRossman 

All, I went over most of the open issues and marked some of them with V2.2. Some should be closed and some may be push to the future. Please go over the list and comment\close:
https://github.com/OpenWaterAnalytics/EPANET/milestone/4

The next step will be to open a pinned issue with the task remaining for the version release.

**Comment by LRossman** [comment] 2019-05-11 15:04
My comments on the list:
#409 - This can be closed as the issue was caused by a mal-formed rule statement.
#251 - This can be closed since `EN_adddemand()` has been added to the API.
#213 - This can be closed since the code already checks the `Hydraul `struct's `OpenHflag `and the `Quality `struct's `OpenQflag `to prevent actions like adding a new node or link while these flags are TRUE.
#137 - This can be closed since it refers to a different branch.
#189 - This can be closed since it has been addressed.
#111 - I think this can be closed since it appears to refer to a MatLab issue.
#109 - This has partially been addressed as the "main" function now used to generate a command line executable displays a correctly formatted message if a user just enters the program name with no arguments. However, the executables are still given different names depending on if the main CMakeLists script or the win build scripts are used to build the executable. I'm not sure if there's some particular reason why the win build scripts use "epanet2.exe" instead of "runepanet.exe" (or vice versa).
#106 - This can be closed as net builder tests have been incorporated into the CI test protocol and the net builder functions have been documented in the new API reference doc.
#12 - This can be closed as testing has verified that sequential and concurrent quality computation perform the same.

**Comment by eladsal** [comment] 2019-11-14 05:16
I'm closing this issue as we are about to close V2.2

**Closed by eladsal** 2019-11-14 05:16 UTC
