### ISSUE TITLE
Ability to insert nodes or links through EPANET Tookit/API

### ISSUE THREAD

**Issue by accumodel** [OpenWaterAnalytics/EPANET#43] opened 2015-11-30 20:22 UTC
The toolkit does not currently support programmatically adding nodes or links after the initial data is read from .inp text file.  This is left to the realm of GUI or other outside tools that manipulate the data before the toolkit consumes it.

Is there any interest in adding this feature to the toolkit?  If so, I can add more comments about some ideas I have to tweak the current code.

**Comment by eladsal** [comment] 2015-11-30 21:51
The ability to build the network, with all elements, from the code is needed.

Currently when the GUI user press the run button the program writes an INP file and calls the DLL which reads the INP file. Strange but this is how it works.

**Comment by accumodel** [comment] 2015-11-30 22:12
It is not strange when you consider that a lot of data error checking is performed when the INP is read back into the engine.  

I think it is only strange because there is likely a better (although maybe more complex) way to do it.

**Comment by samhatchett** [comment] 2015-12-01 17:20
+1

absolutely needed. also requires a full analysis of the way that network topology and state are allocated and retained. I started some of this work in my own branch, but it's nowhere near ready for review or submission; more a prototype for understanding what is likely to break if we do this.

**Comment by samhatchett** [comment] 2015-12-04 04:06
absent objections, I think this issue should be broadened to encompass the ability to programmatically construct a complete network and run a simulation - with no requirement of having an `inp` file. This would mean that the `2.00.12` behavior would have to be replicated through a "factory" that parses the input file and calls into this new API.

**Comment by samhatchett** [comment] 2016-11-21 16:51
Hello again. Folks watching this issue will be excited to see PR #88 

My thanks to @AbelHeinsbroek for submitting. A question for Abel and any others who care to digest - how much of this Issue is covered by the PR? In other words, from a Roadmapping perspective, how much further along will we be, and what work would remain, once the PR is finalized? 

I encourage us all to go over to the PR and look at it in-depth. I've started a review with some detailed comments and suggestions which I hope will be a starting point for good discussion. Hope to get this issue finalized and merged soon!

**Comment by eladsal** [comment] 2016-11-21 17:24
Sure. I suggest we open a new branch for this.

Thanks @AbelHeinsbroek !

**Comment by samhatchett** [comment] 2016-11-21 18:02
Ok, as helpfully suggested by @eladsal I have redirected the base branch for the PR to a new `dev-net-builder` branch. Also I've got a preliminary review on the PR - so I hope everyone will feel at liberty to comment and discuss. 

As to the question of how this fits in with overall roadmapping or project evolution, I think what I'd like to see is for all the `input[n].c` files to be moved into a separate library that uses these new API functions to build the network, rather than modifying epanet's internal state. 

A question to consider: is the set of API functions complete in this regard, to take over responsibility of building a network and setting all properties?

**Comment by AbelHeinsbroek** [comment] 2016-11-21 19:43
Hi all,

Thanks for the feedback! I've mostly developed this set of methods to augment my [EPYNET](https://github.com/vitensTC/epynet) module with the ability to construct and change networks in a very 'Pythonic' manner, for example:

```python
network = Network()
main = network.add_reservoir('in', x=10, y=10)
main.elevation = 10

node = network.add_junction('j1', x=20, y=10)
node.basedemand = 1
node.elevation = 5

pipe = network.add_pipe('p1', 'in', 'j1')
pipe.diameter = 500
pipe.length = 1000
pipe.roughness = 0.1

network.solve()
print(pipe.flow)
```
Which works like a charm.

@samhatchett I think most of the issue is covered by my pull request, although more testing is needed to verify that it works without issue on all platforms, and with all other features, such as control schemes and chemicals, which I have not tested yet. It would be nice to be able to change link and node types, but that would require a lot of 'shuffling' arrays and work.

Refactoring the `input[n].c` to use these new methods would be a good idea, but would require some re-thinking on the current implementation of reallocating memory and shuffling around indexes. 

Regarding those indexes, I would like to propose getting rid of all the index based functions and use object ids instead, as indices are no longer intrinsically linked to objects when the network is modified.

**Comment by samhatchett** [comment] 2018-08-29 14:10
I think everything discussed here has made it into the `dev` branch right? Ok to close?

**Comment by eladsal** [comment] 2018-08-29 14:20
Yes, these APIs were added.

**Closed** 2018-09-05 19:18 UTC
Labels: Roadmap, enhancement
