### ISSUE TITLE
Problems testing output access feature

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#415] opened 2019-03-11 14:40 UTC
I added a test to `test_output.cpp` to exercise the new feature allowing access to the binary output file prior to project close. The test builds and passes on 64 bit, but the build fails on 32 bit because it is unable to link with epanet2.dll that uses the def file. 

I propose we create a build option for compiling with the def file.  Something like `-DBUILD_USE_DEF=ON`.  Rather than having the def file be the default for the MSVC 32 bit build. Thoughts?

**Comment by LRossman** [comment] 2019-03-11 15:23
@michaeltryby could you please post your test file. I'd like to see what the problem is before agreeing to add yet another build option.

**Comment by michaeltryby** [comment] 2019-03-11 15:28
@LRossman have a look at PR #416.

**Comment by michaeltryby** [comment] 2019-03-11 15:45
@LRossman As you can see on Appveyor the 32 bit build fails and the 64 bit build passes.

**Comment by LRossman** [comment] 2019-03-11 16:35
Appveyor indicates that `test_output` is calling functions with decorated names of the form `_imp_EN_xxx` whereas the toolkit's decorated function names are `_EN_xxx`. So where is the `_imp` coming from?

I also noticed that test_output is making calls to `ENR_ init`, `ENR_open`,  `ENR_close`. What are these `ENR` functions? Could they be the source of the problem?

Maybe it would be a better strategy (but less efficient) to add a `EN_copyoutfile` function to give client apps access to a copy of the output file (like was done for the report file) rather than the actual file being used by an open project.

**Comment by michaeltryby** [comment] 2019-03-11 16:56
@LRossman ENR is the prefix used for the output library.  That is the library under test in `test_output.cpp`. It ran fine before calls to epanet2.dll were added for the latest test. I don't know where the `_imp` is coming from.  

I'm pretty sure this is a linking issue related to the def file, since it is running fine for 64 bit and the only difference between the two is the def file. 

I should add that the output library is using cmake's generate_export_header command. So I guess def file dlls and a lib file dlls can't be linked in the same executable.

**Comment by michaeltryby** [comment] 2019-03-11 17:21
@michaeltryby from the link command it looks like the compiler is using the export library `.lib` file to link . The `_imp` is what it's looking for and it is complaining because it can't find it since the dll was compiled with the `.def` file. 

How do you tell cmake to link using a `.def` file?

**Comment by LRossman** [comment] 2019-03-11 17:29
Here's a thought. Since you (@michaeltryby ) have already included all of the functions any app would need to access the output file in your output library, why don't we just incorporate those into the toolkit library and forget about manipulating the opening/closing of the output file. The functions I'm referring to are: `EN_getenergyusage, EN_getnodeseries, EN_getlinkseries, EN_getnoderesults` (your `EN_getNodeAttribute`), `EN_getlinkresults, EN_getnoderesult`, and `EN_getlinkresult`. I will volunteer to do so.

Regarding the cmake question, these lines are used to build the library using a .def file:
 ```
add_library(epanet2 SHARED ${EPANET_LIB_ALL} ${PROJECT_SOURCE_DIR}/include/epanet2.def)
set_source_files_properties(${PROJECT_SOURCE_DIR}/include/epanet2.def PROPERTIES_HEADER_FILE_ONLY TRUE)
```

**Comment by michaeltryby** [comment] 2019-03-11 17:46
@LRossman Yeah we have an output library for SWMM too. It's called by python for reg tests and being used in the new UIs.  

Interesting thought. The only problem I see is that the toolkit API is already very large. It's not necessary to deliver all this functionality in one monolithic dll. Here is a thought that @samhatchett  proposed some time ago. Why don't we take the binary output file writing functions currently in the engine and move them out to the output library? 

As far as cmake goes, that doesn't answer my question. We know how to build a dll using a .def file, the question is how to link against it using cmake?  Like why this test is failing right now.

**Comment by LRossman** [comment] 2019-03-11 19:26
@michaeltryby I sort of agree about the size of the toolkit API being too large (I believe I complained about that months ago, before we added even more functions to it). And I thought of another use case where the ablity to make a copy of the output file while keeping the project open is needed. That would be in a UI that wants to implement a scenario manager or simply be able to plot time series from two or more runs on the same graph. So I now think that an `EN_copyoutfile` is needed more than the output file access functions.

I can try taking one of the test files which I've linked successfully with the def file dll in the Visual Studio IDE and instead build it using cmake. Would that serve to answer your question?

**Comment by michaeltryby** [comment] 2019-03-11 19:46
@LRossman I have been trying to isolate this build problem so I can unambiguously attribute it to the .def file, but as of yet my attempts to do so have failed. My thinking now, is that it is an issue with Visual Studio 2017. 

> I can try taking one of the test files which I've linked successfully with the def file dll in the Visual Studio IDE and instead build it using cmake. Would that serve to answer your question? 

Yes that would be helpful. But why don't you use `test_output.cpp` since that is the test we are having issues with.

**Comment by michaeltryby** [comment] 2019-03-11 20:49
@LRossman Figured it out. The `DLLEXPORT` definitions for epanet2.dll and epanet-output.dll were clobbering each other. Though, I'm not sure why this only affected the 32-bit build.

**Comment by LRossman** [comment] 2019-03-11 21:12
@michaeltryby I notice the `DLLEXPORT` definition for the toolkit includes `__stdcall `while the one for the output library doesn't. And `#include "epanet2_2.h"` comes after `#include "epanet_output.h"` in `test_output.cpp`, meaning DLLEXPORT is being defined without` __stdcall`. So I wonder if this means the linker is expecting the `__cdecl `convention for the toolkit functions when they were built using `__stdcall`?

**Comment by LRossman** [comment] 2019-03-11 21:23
Even if the problem with the `test_output.cpp` issue is resolved, there is still the issue if an app should be allowed to access an open project's output file or not. What if the app opens the file and then tries to use the toolkit to make another analysis before closing it. The toolkit function `EN_initQ` will fail since it can't re-open the output file. If instead the app simply gets a copy of the output file to work with then this situation is avoided. I'm leaning towards walking back this recent change and going with the `EN_copyoutfile` approach instead. Does anyone have an opinion on this?

**Comment by michaeltryby** [comment] 2019-03-11 21:47
@LRossman When weighing issues like this I think about when such an error would most likely get detected -- either during development or when in application is live and in the wild. If someone developing a client application didn't close the output file prior to running another analysis this would most likely be identified as an issue during development. Making it less serious in my mind. 

The other thought I have is that the user may not want to use the same output file over again, they may want to work with several output files (imagining someone running and comparing scenarios). So we need a way to easily specify the creation of an output file for the current model run. 

Lastly, unlike report files, output files can be very large. This makes copying them potentially expensive in terms of process time and storage space.  

So I would stop second guessing it, I think the solution already checked in is a pretty decent one.

**Closed** 2019-03-15 10:37 UTC
Labels: bug
